{% set name = "bowler" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cdb85ce2e7bd545802a15d755d1daf2b6a125429355c50d2019a9f35d63e45db

build:
  noarch: python
  number: 0
  entry_points:
    - bowler = bowler.main:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.6.0
  run:
    - attrs
    - click
    - fissix
    - moreorless >=0.2.0
    - python
    - volatile

test:
  imports:
    - bowler
    - bowler.tests
  commands:
    - bowler --help
    - python -m unittest -v bowler.tests

about:
  home: https://pybowler.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Safe code refactoring for modern Python projects
  dev_url: https://github.com/facebookincubator/bowler

extra:
  recipe-maintainers:
    - nicoddemus
